### ISSUE TITLE
0.5 sürümü anlık olarak gündüz moduna geçiş yapıyor

### ISSUE THREAD

**Issue by FatihErdem** [canarslan12/youreads#9]
0.4 sürümünde gece modu sıkıntısız aktif kalıyordu. Ama 0.5 sürümünde sayfa yenilendikten hemen sonra gündüz moduna geçiş yapıp ardından gece moduna geçiyor. Her sayfa geçişinde bu gerçekleşiyor.

**Comment by canarslan12** [comment]
bu da site tarafında düzelmesi muhtemel durum

**Comment by FatihErdem** [comment]
Sebebi anlaşıldı. Eklenti ayarından gece modu seçiliyken ama siteden seçili değilken bu sorun oluyor. Her iki tarafta da gece modu seçilirse sorun kalmıyor. Ancak sadece eklentiden seçenler için sorun olur.

**Comment by FatihErdem** [comment]
Ancak site zaten zaman zaman sıfırlıyor tema ayarını. eklenti siteye ilk girdiğinde bu ayarı kontrole edebilirse sorun çözülebilir diye düşünüyorum.

**Comment by canarslan12** [comment]
1 hafta içinde site tarafında düzelmemesi durumunda düzeltilecek
